import { createHash, randomUUID } from "node:crypto";
import type { Pool } from "pg";
import { OperationalApiError } from "./response";
import { enqueueWorldResolution, publishMathEvent } from "../math/orchestration";

export class WorldOperations {
  constructor(private readonly pool: Pool) {}
  private async admin(actor: string, action: string, objectId: string, reason: string) {
    const r = await this.pool.query(`SELECT role FROM "User" WHERE id=$1 AND status='ACTIVE' AND role IN ('ADMIN','MODERATOR')`, [actor]);
    if (!r.rowCount) throw new OperationalApiError(403, "FORBIDDEN");
    await this.pool.query(`INSERT INTO "AdminAction" (id,"adminId",action,reason) VALUES ($1,$2,$3,$4)`, [randomUUID(), actor, action, reason]);
    await this.pool.query(`INSERT INTO "AuditLog" (id,"actorId",action,"objectType","objectId","occurredAt") VALUES ($1,$2,$3,'World',$4,clock_timestamp())`, [randomUUID(), actor, action, objectId]);
  }
  async listEvents(actor: string, cursor?: string | null, filters?: { category?: string | null; status?: string | null }) {
    const category = filters?.category?.trim() || null;
    const status = filters?.status?.trim() || null;
    const r = await this.pool.query(`SELECT e.id,e.title,e.description,e."sourceUrl",e."resolutionCriteria",e."opensAt",e."closesAt",e."startsAt",e.status,c.slug AS category,COALESCE(jsonb_agg(jsonb_build_object('id',o.id,'code',o.code,'label',o.label,'position',o.position) ORDER BY o.position) FILTER (WHERE o.id IS NOT NULL),'[]') opportunities FROM "WorldEvent" e JOIN "WorldCategory" c ON c.id=e."categoryId" LEFT JOIN "WorldOpportunity" o ON o."eventId"=e.id WHERE (e.status <> 'DRAFT' OR e."createdById"=$1) AND ($2::uuid IS NULL OR e.id>$2) AND ($3::text IS NULL OR c.slug=$3) AND ($4::text IS NULL OR e.status=$4) GROUP BY e.id,c.slug ORDER BY e.id LIMIT 21`, [actor, cursor ?? null, category, status]);
    return { items: r.rows.slice(0,20), nextCursor: r.rows.length>20 ? Buffer.from(r.rows[19].id).toString("base64url") : null };
  }
  async createEvent(actor: string, input: { category: string; title: string; description?: string | undefined; sourceUrl?: string | undefined; resolutionCriteria: string; opensAt: string; closesAt: string; startsAt?: string | undefined; opportunities: { code: string; label: string }[] }, reason: string) {
    const id=randomUUID(); const categoryId=randomUUID(); const c=await this.pool.connect();
    try { await c.query("BEGIN"); await this.admin(actor,"WORLD_EVENT_DRAFT_CREATE",id,reason); await c.query(`INSERT INTO "WorldCategory" (id,slug,name) VALUES ($1,$2,$2) ON CONFLICT (slug) DO UPDATE SET name=EXCLUDED.name`,[categoryId,input.category]); const cr=await c.query<{id:string}>(`SELECT id FROM "WorldCategory" WHERE slug=$1`,[input.category]); const category = cr.rows[0]; if (!category) throw new OperationalApiError(500,"INTERNAL_ERROR"); await c.query(`INSERT INTO "WorldEvent" (id,"categoryId",title,description,"sourceUrl","resolutionCriteria","opensAt","closesAt","startsAt",status,"createdById") VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,'DRAFT',$10)`,[id,category.id,input.title,input.description??null,input.sourceUrl??null,input.resolutionCriteria,input.opensAt,input.closesAt,input.startsAt??null,actor]); for (const [i,o] of input.opportunities.entries()) await c.query(`INSERT INTO "WorldOpportunity" (id,"eventId",code,label,position) VALUES ($1,$2,$3,$4,$5)`,[randomUUID(),id,o.code,o.label,i]); await c.query("COMMIT"); return {id,status:"DRAFT"}; } catch(e){await c.query("ROLLBACK");throw e;} finally{c.release();}
  }
  async publishEvent(actor:string,eventId:string,reason:string){await this.admin(actor,"WORLD_EVENT_PUBLISH",eventId,reason);const c=await this.pool.connect();try{await c.query("BEGIN");const result=await c.query(`UPDATE "WorldEvent" SET status='PUBLISHED',"updatedAt"=clock_timestamp() WHERE id=$1 AND status='DRAFT' AND "createdById"=$2 RETURNING id`,[eventId,actor]);if(!result.rowCount)throw new OperationalApiError(404,"NOT_FOUND");await publishMathEvent(c,{eventType:"WORLD_EVENT_PUBLISHED",aggregateType:"WorldEvent",aggregateId:eventId,payload:{actorId:actor},idempotencyKey:"world-event-published:"+eventId});await c.query("COMMIT");return{eventId,status:"PUBLISHED"};}catch(e){await c.query("ROLLBACK");throw e;}finally{c.release();}}
  async predict(actor: string, eventId: string, opportunityId: string, confidence: number) {
    const e=await this.pool.query<{status:string; closesAt: Date; opensAt: Date}>(`SELECT status,"opensAt","closesAt" FROM "WorldEvent" WHERE id=$1`,[eventId]);
    if(!e.rowCount) throw new OperationalApiError(404,"NOT_FOUND");
    const event=e.rows[0]!;
    const now=Date.now();
    if(event.status !== "PUBLISHED" || now < event.opensAt.getTime() || now >= event.closesAt.getTime()-10*60*1000) throw new OperationalApiError(409,"CONFLICT");
    const opportunity=await this.pool.query(`SELECT 1 FROM "WorldOpportunity" WHERE id=$1 AND "eventId"=$2`,[opportunityId,eventId]);
    if(!opportunity.rowCount) throw new OperationalApiError(422,"RULE_VIOLATION");
    const id=randomUUID(); const predictedAt=new Date(); const hash=createHash("sha256").update(JSON.stringify({id,eventId,opportunityId,actor,confidence,predictedAt:predictedAt.toISOString()})).digest("hex"); const client=await this.pool.connect(); try { await client.query("BEGIN"); await client.query(`INSERT INTO "WorldPrediction" (id,"eventId","opportunityId","predictorId",confidence,"confirmedAt","predictedAt","snapshotHash") VALUES ($1,$2,$3,$4,$5,clock_timestamp(),$6,$7)`,[id,eventId,opportunityId,actor,confidence,predictedAt,hash]); await publishMathEvent(client,{eventType:"WORLD_PREDICTION_CONFIRMED",aggregateType:"WorldEvent",aggregateId:eventId,payload:{predictionId:id,predictorId:actor},idempotencyKey:"world-prediction:"+id}); await client.query("COMMIT"); return {id,snapshotHash:hash}; } catch(e){await client.query("ROLLBACK");throw e;} finally{client.release();}
  }
  async resolve(actor:string,eventId:string,input:{state:"TEST"|"OFFICIAL"|"CANCELLED"|"VOID";outcomeOpportunityId?:string | undefined;rationale:string}) { await this.admin(actor,"WORLD_EVENT_RESOLVE",eventId,input.rationale); const c=await this.pool.connect(); try {await c.query("BEGIN"); await c.query(`INSERT INTO "WorldResolution" (id,"eventId","outcomeOpportunityId",state,rationale,"resolvedById") VALUES ($1,$2,$3,$4,$5,$6) ON CONFLICT ("eventId") DO UPDATE SET state=EXCLUDED.state,"outcomeOpportunityId"=EXCLUDED."outcomeOpportunityId",rationale=EXCLUDED.rationale,"resolvedById"=EXCLUDED."resolvedById", "resolvedAt"=clock_timestamp()`,[randomUUID(),eventId,input.outcomeOpportunityId??null,input.state,input.rationale,actor]); await c.query(`UPDATE "WorldEvent" SET status=$1,"updatedAt"=clock_timestamp() WHERE id=$2`,[input.state==='OFFICIAL'||input.state==='TEST'?'RESOLVED':input.state,eventId]); await enqueueWorldResolution(c,eventId,input.outcomeOpportunityId??null,input.state,input.rationale); await c.query("COMMIT"); return {eventId,state:input.state}; } catch(e){await c.query("ROLLBACK");throw e;} finally{c.release();} }
  async comment(actor:string,eventId:string,body:string){const id=randomUUID();await this.pool.query(`INSERT INTO "WorldComment" (id,"eventId","authorId",body) VALUES ($1,$2,$3,$4)`,[id,eventId,actor,body]);return{id};}
  async react(actor:string,eventId:string,kind:string){await this.pool.query(`INSERT INTO "WorldReaction" ("eventId","userId",kind) VALUES ($1,$2,$3) ON CONFLICT DO NOTHING`,[eventId,actor,kind]);return{eventId,kind};}
  async adminUsers(actor:string, cursor?:string|null){await this.admin(actor,"ADMIN_USERS_READ",actor,"authorized listing");const r=await this.pool.query<{id:string} & Record<string,unknown>>(`SELECT id,status,role,"createdAt" FROM "User" WHERE ($1::uuid IS NULL OR id>$1) ORDER BY id LIMIT 21`,[cursor??null]);const last=r.rows[19];return{items:r.rows.slice(0,20),nextCursor:r.rows.length>20&&last?Buffer.from(last.id).toString("base64url"):null};}
  async userAction(actor:string,target:string,action:string,reason:string){await this.admin(actor,`USER_${action}`,target,reason);if(["SUSPEND","UNSUSPEND"].includes(action)) await this.pool.query(`UPDATE "User" SET status=$1 WHERE id=$2`,[action==='SUSPEND'?'SUSPENDED':'ACTIVE',target]);return{targetId:target,action};}
}
