import { brierBinary as canonicalBrierBinary, brierMulticlass as canonicalBrierMulticlass, binaryBaseline, clipProbability, consensusLeaveOneOut, estimateRadar, radarState, temporalWeight, worldState } from "../math-engine";
export { clipProbability, canonicalBrierBinary as brierBinary, canonicalBrierMulticlass as brierMulticlass, estimateRadar, temporalWeight };
export type { EvidenceState } from "../math-engine";
export function baselineBrier(outcomes: readonly (0 | 1)[]): number { if (!outcomes.length) throw new Error("NO_OUTCOMES"); const base=binaryBaseline(outcomes); return outcomes.reduce((sum: number,outcome)=>sum+(base-Number(outcome))**2,0)/outcomes.length; }
export function temporalWeights(times: readonly number[], now: number, lambda: number): number[] { if(!Number.isFinite(now)||times.some((time)=>!Number.isFinite(time))||lambda<0||!Number.isFinite(lambda)) throw new Error("INVALID_TEMPORAL_INPUT"); const raw=times.map((time)=>Math.exp(-lambda*Math.max(0,now-time))); const total=raw.reduce((sum,value)=>sum+value,0); return total?raw.map((value)=>value/total):[]; }
export function effectiveSampleSize(weights: readonly number[]): number { if(weights.some((weight)=>!Number.isFinite(weight)||weight<0)) throw new Error("INVALID_WEIGHTS"); if(!weights.length)return 0; const total=weights.reduce((sum,weight)=>sum+weight,0); return total?total**2/weights.reduce((sum,weight)=>sum+weight**2,0):0; }
export function pooledConsensus(probabilities: readonly number[]): number { if (!probabilities.length) throw new Error("NO_FORECASTS"); const clipped=probabilities.map((value)=>clipProbability(value)); const result=consensusLeaveOneOut(clipped.map((probability,index)=>({predictorId:String(index),probability}))); if(result!==null)return result; return clipProbability(clipped.reduce((sum,p)=>sum+p,0)/clipped.length); }
/** Legacy numerical helper. Official leave-one-out publication still requires Q=5 via consensusLeaveOneOut. */
export function leaveOneOutConsensus(probabilities: readonly number[], index: number): number { if(!Number.isInteger(index)||index<0||index>=probabilities.length)throw new Error("INVALID_INDEX"); const rest=probabilities.filter((_,i)=>i!==index); if(!rest.length)throw new Error("INSUFFICIENT_LEAVE_ONE_OUT"); return pooledConsensus(rest); }
export function confidenceInterval95(values: readonly number[]): {estimate:number;lower:number;upper:number;margin:number} { if(!values.length)throw new Error("NO_VALUES"); const estimate=values.reduce((sum,value)=>sum+value,0)/values.length; const variance=values.length>1?values.reduce((sum,value)=>sum+(value-estimate)**2,0)/(values.length-1):0; const margin=1.96*Math.sqrt(variance/values.length); return {estimate,lower:estimate-margin,upper:estimate+margin,margin}; }
export function shrink(value:number,prior:number,effectiveN:number,priorStrength:number):number { if(![value,prior,effectiveN,priorStrength].every(Number.isFinite)||effectiveN<0||priorStrength<0)throw new Error("INVALID_SHRINKAGE"); return (effectiveN*value+priorStrength*prior)/(effectiveN+priorStrength||1); }
export const worldEvidenceState=worldState;
export const radarEvidenceState=(nEff:number,ra:number,rb:number,interval:{lower:number;upper:number})=>radarState(nEff,ra,rb,interval.lower>0||interval.upper<0);
export const radarGammaModel=(mu:number,alpha:number,beta:number,gamma:number,residual:number)=>mu+alpha+beta+gamma+residual;
