"use client";

import { useCallback, useEffect, useMemo, useState } from "react";

type User = { id: string; status: string; role: string; createdAt: string };
type EventOpportunity = { id: string; code: string; label: string; position: number };
type WorldEvent = { id: string; title: string; description?: string | null; category: string; status: string; opensAt: string; closesAt: string; opportunities: EventOpportunity[] };
type Audit = { id: string; actorId: string | null; action: string; objectType: string; objectId: string; occurredAt: string };
type Panel = "overview" | "users" | "events" | "audit";

async function getJson<T>(url: string): Promise<T> { const response = await fetch(url, { credentials: "same-origin", cache: "no-store" }); if (!response.ok) throw new Error(response.status === 403 ? "Acesso administrativo necessário." : "Não foi possível carregar os dados."); return response.json() as Promise<T>; }
async function postJson<T>(url: string, body: unknown): Promise<T> { const response = await fetch(url, { method: "POST", credentials: "same-origin", headers: { "Content-Type": "application/json", "Idempotency-Key": crypto.randomUUID() }, body: JSON.stringify(body) }); if (!response.ok) throw new Error("Não foi possível concluir a operação administrativa."); return response.json() as Promise<T>; }
function date(value: string) { return new Intl.DateTimeFormat("pt-BR", { dateStyle: "short", timeStyle: "short" }).format(new Date(value)); }

export function CommandCenter() {
  const [panel, setPanel] = useState<Panel>("overview"); const [users, setUsers] = useState<User[]>([]); const [events, setEvents] = useState<WorldEvent[]>([]); const [audit, setAudit] = useState<Audit[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [notice, setNotice] = useState<string | null>(null); const [showEventForm, setShowEventForm] = useState(false);
  const load = useCallback(async () => { setLoading(true); setError(null); try { const [userData, eventData, auditData] = await Promise.all([getJson<{ items: User[] }>("/api/v1/admin/users"), getJson<{ items: WorldEvent[] }>("/api/v1/world/events"), getJson<{ items: Audit[] }>("/api/v1/admin/audit")]); setUsers(userData.items); setEvents(eventData.items); setAudit(auditData.items); } catch (cause) { setError(cause instanceof Error ? cause.message : "Não foi possível carregar o quartel general."); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  const activeEvents = useMemo(() => events.filter((item) => item.status === "PUBLISHED").length, [events]); const suspendedUsers = useMemo(() => users.filter((item) => item.status === "SUSPENDED").length, [users]);
  async function changeUser(id: string, action: "SUSPEND" | "UNSUSPEND") { try { await postJson(`/api/v1/admin/users/${id}/action`, { action, reason: "Ação executada no Command Center." }); setNotice("Ação registrada na trilha de auditoria."); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Ação recusada."); } }
  async function resolveEvent(event: WorldEvent, state: "TEST" | "CANCELLED") { try { await postJson(`/api/v1/world/events/${event.id}/resolve`, { state, rationale: state === "CANCELLED" ? "Cancelamento administrativo." : "Fechamento de teste administrativo." }); setNotice(state === "CANCELLED" ? "Evento cancelado." : "Evento encerrado."); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Não foi possível atualizar o evento."); } }
  return <main id="conteudo" className="social-main container"><div className="social-heading"><div><span className="eyebrow">Acesso restrito · ADMIN</span><h1 className="display">Quartel General</h1><p className="muted">Comando operacional do ORVOK: pessoas, eventos, auditoria e sinais do sistema.</p></div><button className="button" type="button" onClick={() => void load()} disabled={loading}>{loading ? "Atualizando…" : "Atualizar dados"}</button></div><nav className="admin-tabs" aria-label="Módulos administrativos">{(["overview", "users", "events", "audit"] as Panel[]).map((item) => <button key={item} type="button" className={panel === item ? "button" : "button button-secondary"} onClick={() => setPanel(item)}>{item === "overview" ? "Visão geral" : item === "users" ? "Usuários" : item === "events" ? "Eventos" : "Auditoria"}</button>)}</nav>{error && <p className="form-message" data-kind="error" role="alert">{error}</p>}{notice && <p className="form-message" role="status">{notice}</p>}{panel === "overview" && <Overview users={users} activeEvents={activeEvents} suspendedUsers={suspendedUsers} audit={audit} />}{panel === "users" && <Users users={users} onAction={changeUser} />}{panel === "events" && <Events events={events} showForm={showEventForm} onShowForm={setShowEventForm} onRefresh={load} onResolve={resolveEvent} onNotice={setNotice} />}{panel === "audit" && <Audit items={audit} />}</main>;
}

function Overview({ users, activeEvents, suspendedUsers, audit }: { users: User[]; activeEvents: number; suspendedUsers: number; audit: Audit[] }) { return <><section className="stat-grid"><Stat label="Usuários cadastrados" value={String(users.length)} hint="dados reais" /><Stat label="Eventos publicados" value={String(activeEvents)} hint="abertos agora" /><Stat label="Usuários suspensos" value={String(suspendedUsers)} hint="ação necessária" /><Stat label="Ações recentes" value={String(audit.length)} hint="últimos registros" /></section><section className="admin-grid"><article className="social-card"><span className="eyebrow">Linha do tempo</span><h2>Atividade operacional</h2>{audit.length ? <ol className="admin-timeline">{audit.slice(0, 8).map((item) => <li key={item.id}><strong>{item.action}</strong><span>{item.objectType} · {date(item.occurredAt)}</span></li>)}</ol> : <p className="muted">Nenhuma ação registrada ainda.</p>}</article><article className="social-card"><span className="eyebrow">Leitura rápida</span><h2>Estado do sistema</h2><p className="muted">Painel conectado às tabelas reais de usuários, eventos e auditoria. Pesquisas, mensagens e métricas entram nesta mesma base.</p></article></section></>; }

function Users({ users, onAction }: { users: User[]; onAction: (id: string, action: "SUSPEND" | "UNSUSPEND") => Promise<void> }) { const [query, setQuery] = useState(""); const filtered = users.filter((item) => `${item.id} ${item.role} ${item.status}`.toLowerCase().includes(query.toLowerCase())); return <section className="social-card"><header className="social-section-title"><span className="eyebrow">Diretório real</span><h2>Usuários e permissões</h2></header><label className="field"><span>Buscar</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="ID, papel ou estado" /></label><div className="table-wrap"><table><thead><tr><th>ID</th><th>Papel</th><th>Estado</th><th>Cadastro</th><th>Ações</th></tr></thead><tbody>{filtered.map((item) => <tr key={item.id}><td><code>{item.id.slice(0, 8)}…</code></td><td><span className="status-pill">{item.role}</span></td><td>{item.status}</td><td>{date(item.createdAt)}</td><td><button className="text-link" type="button" onClick={() => void onAction(item.id, item.status === "SUSPENDED" ? "UNSUSPEND" : "SUSPEND")}>{item.status === "SUSPENDED" ? "Reativar" : "Suspender"}</button></td></tr>)}</tbody></table></div>{!filtered.length && <p className="muted">Nenhum usuário encontrado.</p>}</section>; }

function Events({ events, showForm, onShowForm, onRefresh, onResolve, onNotice }: { events: WorldEvent[]; showForm: boolean; onShowForm: (value: boolean) => void; onRefresh: () => Promise<void>; onResolve: (event: WorldEvent, state: "TEST" | "CANCELLED") => Promise<void>; onNotice: (value: string) => void }) { return <><section className="social-card"><div className="social-section-title"><div><span className="eyebrow">Operação mundial</span><h2>Eventos e resultados</h2></div><button className="button" type="button" onClick={() => onShowForm(!showForm)}>{showForm ? "Fechar formulário" : "Cadastrar evento"}</button></div>{showForm && <EventForm onCreated={async () => { onShowForm(false); onNotice("Evento publicado e auditado."); await onRefresh(); }} />}</section><section className="social-card"><div className="table-wrap"><table><thead><tr><th>Evento</th><th>Categoria</th><th>Estado</th><th>Período</th><th>Ações</th></tr></thead><tbody>{events.map((event) => <tr key={event.id}><td><strong>{event.title}</strong><br /><span className="muted">{event.opportunities.length} opções</span></td><td>{event.category}</td><td><span className="status-pill">{event.status}</span></td><td>{date(event.opensAt)}<br />até {date(event.closesAt)}</td><td>{event.status === "PUBLISHED" && <><button className="text-link" type="button" onClick={() => void onResolve(event, "TEST")}>Encerrar</button><button className="text-link" type="button" onClick={() => void onResolve(event, "CANCELLED")}>Cancelar</button></>}</td></tr>)}</tbody></table></div>{!events.length && <p className="muted">Nenhum evento cadastrado.</p>}</section></>; }

function EventForm({ onCreated }: { onCreated: () => Promise<void> }) { const [busy, setBusy] = useState(false); async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); const fields = new FormData(event.currentTarget); try { await postJson("/api/v1/world/events", { category: String(fields.get("category")), title: String(fields.get("title")), description: String(fields.get("description") || ""), resolutionCriteria: String(fields.get("resolutionCriteria")), opensAt: new Date(String(fields.get("opensAt"))).toISOString(), closesAt: new Date(String(fields.get("closesAt"))).toISOString(), opportunities: [{ code: "A", label: String(fields.get("optionA")) }, { code: "B", label: String(fields.get("optionB")) }], reason: String(fields.get("reason")) }); await onCreated(); } finally { setBusy(false); } } return <form className="admin-form" onSubmit={(event) => void submit(event)}><div className="admin-form-grid"><label className="field"><span>Categoria</span><input name="category" required placeholder="Clima" /></label><label className="field"><span>Título</span><input name="title" required /></label><label className="field"><span>Abre em</span><input name="opensAt" type="datetime-local" required /></label><label className="field"><span>Fecha em</span><input name="closesAt" type="datetime-local" required /></label><label className="field"><span>Opção A</span><input name="optionA" required /></label><label className="field"><span>Opção B</span><input name="optionB" required /></label></div><label className="field"><span>Critério de resolução</span><textarea name="resolutionCriteria" required rows={3} /></label><label className="field"><span>Motivo administrativo</span><input name="reason" required minLength={3} /></label><button className="button" disabled={busy}>{busy ? "Publicando…" : "Publicar evento"}</button></form>; }

function Audit({ items }: { items: Audit[] }) { return <section className="social-card"><header className="social-section-title"><span className="eyebrow">Imutável</span><h2>Trilha de auditoria</h2></header><div className="table-wrap"><table><thead><tr><th>Ação</th><th>Objeto</th><th>Ator</th><th>Quando</th></tr></thead><tbody>{items.map((item) => <tr key={item.id}><td>{item.action}</td><td>{item.objectType}<br /><code>{item.objectId.slice(0, 8)}…</code></td><td><code>{item.actorId?.slice(0, 8) ?? "sistema"}…</code></td><td>{date(item.occurredAt)}</td></tr>)}</tbody></table></div></section>; }
function Stat({ label, value, hint }: { label: string; value: string; hint: string }) { return <div className="social-card stat"><span className="eyebrow">{label}</span><strong>{value}</strong><span className="muted">{hint}</span></div>; }
